### ISSUE TITLE
MAINT: clean up `data_builder.py`

### ISSUE THREAD

**Issue by eigenfoo** [eigenfoo/dirichlet-embeddings#8]
Now that we've agreed to preprocess the data into something like `sample_data.txt` all beforehand, it is no longer clear to me what use `data_builder.py` serves. Is it safe to remove?

EDIT: Actually, I now see that it's the script that is printing out `sample_data.txt` files. We should write it better with docstrings and cleaner code, so that it's obvious that that's its only function.

**Comment by Jped** [comment]
In hind site, things could have been made cleaner.
Now that this script is going to be run and done having it built as a class is unnecessary; however, I am for leaving it as it is right now as it does work. 
I am going to be calling the create_word_dict.py directly into the data_builder.py so that we only need to call one python script to create all the data.
Alternatively, if you think it will help we can call the shell script also in the data_builder.py so there is actually only one script to be called.

**Comment by Jped** [comment]
I cleaned it up and moved create_word_dict into data_builder.
It still saves a pickle just so we have it later down the road when we want to look back what a word corresponds to an id.
Let me know if it is more readable... it is a personal goal of mine to make cleaner code so im open to constructive comments ;).

**Comment by eigenfoo** [comment]
Readable enough for now! 😄

Just FYI, you could run `pycodestyle` on your code which will let you know of any PEP8 violations. I see some lying around but I won't make too big a fuss about it. Closing now.

**Comment by eigenfoo** [comment]
Also, I hate to nitpick but you asked for criticism so uh

Next time you should open up a new branch and PR for your changes. That way I can review your code within the issue/PR: currently I'd have to open up a new issue PR for you to actually give line-by-line comments. Just something to keep in mind going forward.
